Repository ec-myers/the-screening-room, pull requests merged in 2019-10, with the labels that each got.

#2 Adds import statements for redux boilerplate
  src/actions/index.js
  src/containers/index.js
  src/index.js
  src/reducers/index.js
Labels: documentation

#5 Add fetching calls of cleaned up data and try/catch them in App
  src/apiCalls/apiCalls.js
  src/components/App/App.js
Labels: documentation, enhancement

#15 Add box shadow to MovieCard components, fix alignment of container, a…
  src/components/App/App.scss
  src/components/Container/Container.scss
  src/components/MovieCard/MovieCard.js
  src/components/MovieCard/MovieCard.scss
Labels: enhancement

#16 Add image backdrop to home page and some styling
  src/components/AccessModal/AccessModal.js
  src/components/AccessModal/AccessModal.scss
  src/components/App/App.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/SignUpForm/SignUpForm.js
Labels: documentation, enhancement

#18 Add micro-interactions and general adjustments to homepage
  src/actions/index.js
  src/components/AccessModal/AccessModal.scss
  src/components/MovieCard/MovieCard.js
  src/components/MovieCard/MovieCard.scss
  src/components/Movies/Movies.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/reducers/movies.js
Labels: enhancement

#19 Form validation errors
  src/actions/index.js
  src/apiCalls/apiCalls.js
  src/components/App/App.js
  src/components/LoginForm/LoginForm.js
  src/components/SignUpForm/SignUpForm.js
  src/reducers/errMsg.js
  src/reducers/errMsg.test.js
  src/reducers/index.js
Labels: enhancement

#23 Edb homepage
  src/apiCalls/apiCalls.js
  src/components/AccessModal/AccessModal.scss
  src/components/App/App.js
  src/components/MovieCard/MovieCard.js
  src/components/MovieCard/MovieCard.scss
  src/components/SelectedMovie/SelectedMovie.js
  src/components/SelectedMovie/SelectedMovie.scss
Labels: documentation, enhancement

#24 Add media queries to movies section
  src/components/Container/Container.scss
  src/components/MovieCard/MovieCard.scss
  src/components/Nav/Nav.scss
  src/components/SelectedMovie/SelectedMovie.scss
Labels: enhancement

#28 Vr testing 2
  src/actions/index.js
  src/components/AccessModal/AccessModal.js
  src/components/AccessModal/AccessModal.test.js
  src/components/App/App.js
  src/components/App/__snapshots__/App.test.js.snap
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/Nav/Nav.test.js
  src/components/SelectedMovie/SelectedMovie.js
  src/components/SelectedMovie/SelectedMovie.test.js
  src/components/SelectedMovie/__snapshots__/SelectedMovie.test.js.snap
  src/components/SignUpForm/SignUpForm.js
  src/components/SignUpForm/SignUpForm.test.js
  src/components/SignUpForm/__snapshots__/SignUpForm.test.js.snap
  src/reducers/user.js
Labels: documentation, enhancement

#29 Fix the nav-buttons, but also make them NavLinks that stay active
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
Labels: enhancement

#31 Vr testing 2
  src/actions/actions.test.js
  src/apiCalls/apiCalls.js
  src/apiCalls/apiCalls.test.js
  src/components/App/App.js
  src/components/Container/Container.js
  src/components/Container/Container.test.js
  src/components/Container/__snapshots__/Container.test.js.snap
  src/components/MovieCard/MovieCard.js
  src/components/MovieCard/MovieCard.test.js
  src/components/MovieCard/__snapshots__/MovieCard.test.js.snap
  src/components/Movies/Movies.js
  src/components/Movies/Movies.scss
  src/components/Movies/Movies.test.js
  src/components/SelectedMovie/SelectedMovie.js
  src/components/SelectedMovie/__snapshots__/SelectedMovie.test.js.snap
  src/components/SignUpForm/SignUpForm.js
  src/components/SignUpForm/SignUpForm.test.js
  src/reducers/errMsg.test.js
  src/reducers/favorites.js
  src/reducers/favorites.test.js
  src/reducers/hasEmailErrMsg.test.js
  src/reducers/movies.js
  src/reducers/movies.test.js
  src/reducers/setLoading.js
  src/reducers/setLoading.test.js
  src/reducers/user.test.js
Labels: enhancement, testing

#33 Vr create account on favorite
  src/actions/index.js
  src/apiCalls/apiCalls.js
  src/components/Container/Container.test.js
  src/components/Container/__snapshots__/Container.test.js.snap
  src/components/MovieCard/MovieCard.js
  src/components/Nav/Nav.js
  src/reducers/favorites.js
  src/reducers/index.js
Labels: bug fix, documentation, enhancement

#32 Fixes, Favs, and localStorage
  src/actions/index.js
  src/apiCalls/apiCalls.js
  src/components/App/App.js
  src/components/Container/Container.js
  src/components/MovieCard/MovieCard.js
  src/components/MovieCard/MovieCard.scss
  src/components/Nav/Nav.js
  src/components/Nav/Nav.test.js
  src/components/Nav/__snapshots__/Nav.test.js.snap
  src/components/SelectedMovie/SelectedMovie.js
  src/components/SelectedMovie/__snapshots__/SelectedMovie.test.js.snap
  src/index.js
  src/localStorage.js
  src/reducers/favorites.js
  src/reducers/index.js
  src/reducers/setRandomWallpaper.js
Labels: bug fix, documentation, enhancement

#35 Testing ecm
  src/actions/actions.test.js
  src/components/LoginForm/LoginForm.test.js
Labels: testing

#36 Vr testing 3
  src/actions/index.js
  src/apiCalls/apiCalls.js
  src/apiCalls/apiCalls.test.js
  src/components/App/__snapshots__/App.test.js.snap
  src/components/Container/Container.js
  src/components/Container/__snapshots__/Container.test.js.snap
  src/components/MovieCard/MovieCard.js
  src/components/Nav/Nav.js
  src/components/SelectedMovie/SelectedMovie.js
  src/components/SignUpForm/SignUpForm.js
  src/components/SignUpForm/SignUpForm.test.js
  src/components/SignUpForm/__snapshots__/SignUpForm.test.js.snap
  src/localStorage.js
  src/reducers/favorites.js
  src/reducers/index.js
  src/reducers/setRandomWallpaper.js
  src/reducers/setRandomWallpaper.test.js
  src/reducers/user.js
  src/reducers/user.test.js
  src/reducers/wallpapers.js
  src/reducers/wallpapers.test.js
Labels: documentation, enhancement, testing

#34 Fix favorites so they're successfully syncing and fix popping errMsg …
  src/Images/addFavorite.png
  src/actions/index.js
  src/apiCalls/apiCalls.js
  src/components/AccessModal/AccessModal.js
  src/components/AccessModal/AccessModal.scss
  src/components/App/App.js
  src/components/App/App.scss
  src/components/Footer/Footer.scss
  src/components/LoginForm/LoginForm.js
  src/components/MovieCard/MovieCard.js
  src/components/MovieCard/MovieCard.scss
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/SelectedMovie/SelectedMovie.scss
  src/index.js
  src/reducers/index.js
  src/reducers/movies.js
  src/reducers/setLoading.js
Labels: bug fix, documentation, enhancement

#37 Improve apiCalls testing coverage
  src/apiCalls/apiCalls.js
  src/apiCalls/apiCalls.test.js
  src/components/SignUpForm/SignUpForm.test.js
Labels: testing

#39 Testing ecm
  src/apiCalls/apiCalls.js
  src/apiCalls/apiCalls.test.js
  src/components/LoginForm/LoginForm.js
  src/components/LoginForm/LoginForm.test.js
  src/components/LoginForm/__snapshots__/LoginForm.test.js.snap
Labels: testing

#38 Vr testing 3
  package-lock.json
  package.json
  src/apiCalls/apiCalls.js
  src/apiCalls/apiCalls.test.js
  src/components/App/App.js
  src/components/App/App.test.js
  src/components/Container/Container.test.js
  src/components/Container/__snapshots__/Container.test.js.snap
  src/components/LoginForm/LoginForm.test.js
  src/components/Nav/__snapshots__/Nav.test.js.snap
  src/components/SignUpForm/SignUpForm.test.js
Labels: bug, testing

#40 Reducers & MovieCards testing
  src/components/MovieCard/MovieCard.test.js
  src/components/MovieCard/__snapshots__/MovieCard.test.js.snap
  src/reducers/errMsg.test.js
  src/reducers/movies.test.js
  src/reducers/setLoading.test.js
Labels: testing

#41 Proptypes ecm
  src/components/LoginForm/LoginForm.js
  src/components/Nav/Nav.js
  src/components/SelectedMovie/SelectedMovie.js
Labels: enhancement

#42 Vr prop types
  src/actions/index.js
  src/components/AccessModal/AccessModal.js
  src/components/App/App.js
  src/components/Container/Container.js
  src/components/Footer/Footer.js
  src/components/LoginForm/LoginForm.js
  src/components/MovieCard/MovieCard.js
  src/components/Nav/Nav.js
  src/components/SignUpForm/SignUpForm.js
Labels: documentation, enhancement, help wanted

#43 Run eslint and eliminate unused variables
  src/apiCalls/apiCalls.js
  src/apiCalls/apiCalls.test.js
  src/components/AccessModal/AccessModal.test.js
  src/components/App/App.test.js
  src/components/Container/Container.test.js
  src/components/LoginForm/LoginForm.test.js
  src/components/MovieCard/MovieCard.test.js
Labels: enhancement

#45 Add favicon
  public/favicon.ico
Labels: enhancement
